jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine #other choose：caffeine
      keyConvertor: fastjson #other choose：fastjson/jackson
      limit: 100
#  remote:
#    default:
#      type: redis
#      keyConvertor: fastjson2 #other choose：fastjson/jackson
#      broadcastChannel: projectA
#      valueEncoder: java #other choose：kryo/kryo5
#      valueDecoder: java #other choose：kryo/kryo5
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${redis.host}
server:
  port: 8081
#      port: ${redis.port}

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 9010
